#! /usr/bin/env python3

import rospy
import numpy as np

n_layers = 5
n_points = 48
r1 = 0.3
r2 = 0.33
layer_height = 0.03
theta_inc = 2 * np.pi / n_points
n=0

f = open('../cfg/fake_print_points.yaml', 'w')
f.write('#DO_NOT_MODIFY: This config file was autogenerated! \n\n')
f.write('waypoints:\n\n')
f.write('  n_layers: '+str(n_layers)+'\n\n')
for i in range(n_layers):
    f.write('  layer'+str(i)+':\n')
    z = layer_height * i
    if i % 2 == 0:
        for j in range(n_points+1):
            theta = theta_inc * j
            x = r1 * np.sin(theta)
            y = r1 * np.cos(theta)
            pose = [x, y, z, 0.0, 0.0, 0.0]
            f.write('    point'+str(n)+': '+str(pose)+'\n')
            n+=1
        for j in range(n_points+1):
            theta = theta_inc * j
            x = r2 * np.sin(theta)
            y = r2 * np.cos(theta)
            pose = [x, y, z, 0.0, 0.0, 0.0]
            f.write('    point'+str(n)+': '+str(pose)+'\n')
            n+=1
    else:
        for j in range(n_points+1):
            theta = theta_inc * j
            x = r1 * np.sin(theta)
            y = r1 * np.cos(theta)
            pose = [x, y, z, 0.0, 0.0, 0.0]
            f.write('    point'+str(n)+': '+str(pose)+'\n')
            n+=1
            x = r2 * np.sin(theta)
            y = r2 * np.cos(theta)
            pose = [x, y, z, 0.0, 0.0, 0.0]
            f.write('    point'+str(n)+': '+str(pose)+'\n')
            n+=1
            temp = r1
            r1 = r2
            r2 = temp
    n = 0
    f.write('\n')