vicon:
    model_list:                                         [hexacopter]
    server_address:                                     "192.168.0.100"
    publish_tf:                                         true